# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shane Smith
description: 'Shane was a candidate for the 2016 Merced City School District Trustee Area One election.'
baseurl: '' # the subpath of your site, e.g. /blog
url: 'http://www.smithformercedschools2016.com' # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Options
permalink: /:title
exclude:
  - 'node_modules'
  - 'bower_components'
  - 'bower.json'
  - 'package.json'
  - 'gulpfile.js'
  - 'Gemfile'
  - 'Gemfile.lock'
sass:
  style: compressed
  load_paths:
    - "_lib/foundation"