# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Joshua Gonzales
description: ''
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://joshua.bio' # the base hostname & protocol for your site
twitter: '@joshuadotbio'
facebook: 'jfmgonzales'
snapchat: 'jjfmg'

# Build settings
markdown: kramdown

# Options
permalink: /:title
exclude:
  - 'node_modules'
  - 'bower_components'
  - 'bower.json'
  - 'package.json'
  - 'gulpfile.js'
  - 'Gemfile'
  - 'Gemfile.lock'
sass:
  style: compressed
  load_paths:
    - "_lib/foundation"